name: photographers_book

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  file_picker: ^6.1.1
  fluro: ^2.0.5
  flutter_portal: ^1.1.4
  fluttertoast: ^8.2.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_pdfviewer: ^23.1.44
  smooth_page_indicator: ^1.1.0
  razorpay_flutter: ^1.3.5
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
